"""add free text destination and pickup coords

Revision ID: 0d9ccf3c5ad6
Revises: b4ccd6b8a2ff
Create Date: 2026-08-29 00:15:24.420857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9ccf3c5ad6'
down_revision: Union[str, Sequence[str], None] = 'b4ccd6b8a2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_requests', sa.Column('destination_text', sa.String(length=150), nullable=True))
    op.add_column('trip_requests', sa.Column('pickup_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('trip_requests', sa.Column('pickup_lng', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_requests', 'pickup_lng')
    op.drop_column('trip_requests', 'pickup_lat')
    op.drop_column('trip_requests', 'destination_text')
    # ### end Alembic commands ###
