"""link bookings to trip plans

Revision ID: 64c3c251afb1
Revises: a1673d891664
Create Date: 2026-08-26 14:07:58.874762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c3c251afb1'
down_revision: Union[str, Sequence[str], None] = 'a1673d891664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('trip_plan_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_trip_plan_id'), 'bookings', ['trip_plan_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'trip_plans', ['trip_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_trip_plan_id'), table_name='bookings')
    op.drop_column('bookings', 'trip_plan_id')
    # ### end Alembic commands ###
