"""add email notification preference

Revision ID: 7902dc6aedfd
Revises: c26ccfd5b52b
Create Date: 2026-08-28 09:13:18.513335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7902dc6aedfd'
down_revision: Union[str, Sequence[str], None] = 'c26ccfd5b52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('email_notifications', sa.Boolean(),
            nullable=False, server_default=sa.true())
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
