"""link budgets to bookings

Revision ID: 9a20676b9c19
Revises: 64c3c251afb1
Create Date: 2026-08-27 09:56:47.030143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a20676b9c19'
down_revision: Union[str, Sequence[str], None] = '64c3c251afb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_budgets', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trip_budgets_booking_id'), 'trip_budgets', ['booking_id'], unique=False)
    op.create_foreign_key(None, 'trip_budgets', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_budgets', type_='foreignkey')
    op.drop_index(op.f('ix_trip_budgets_booking_id'), table_name='trip_budgets')
    op.drop_column('trip_budgets', 'booking_id')
    # ### end Alembic commands ###
