"""add provider daily rate

Revision ID: a1673d891664
Revises: 50441bdca6a5
Create Date: 2026-08-25 17:02:15.121050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1673d891664'
down_revision: Union[str, Sequence[str], None] = '50441bdca6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('guide_profiles', sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide_profiles', 'daily_rate')
    op.drop_column('driver_profiles', 'daily_rate')
    # ### end Alembic commands ###
