"""add sltda registration fields

Revision ID: b4ccd6b8a2ff
Revises: 7902dc6aedfd
Create Date: 2026-08-28 10:05:27.867756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ccd6b8a2ff'
down_revision: Union[str, Sequence[str], None] = '7902dc6aedfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide_profiles', sa.Column('sltda_registered', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('guide_profiles', sa.Column('sltda_number', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide_profiles', 'sltda_number')
    op.drop_column('guide_profiles', 'sltda_registered')
    # ### end Alembic commands ###
